name: Kotlin hw 4 check

on:
    pull_request:
        types:
        - opened
        - synchronize

jobs:
    build:
        runs-on: [self-hosted, kotlin]
        timeout-minutes: 10
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: 17
              distribution: adopt
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
        - name: Build with Gradle
          run: ./gradlew build
