package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.Repository -o ./repository_mock_test.go -n RepositoryMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements Repository
type RepositoryMock struct {
	t minimock.Tester

	funcGetAllSubjects          func() (sa1 []string, b1 bool)
	inspectFuncGetAllSubjects   func()
	afterGetAllSubjectsCounter  uint64
	beforeGetAllSubjectsCounter uint64
	GetAllSubjectsMock          mRepositoryMockGetAllSubjects

	funcGetAllSubjectsInfo          func() (sa1 []subjectInfo, b1 bool)
	inspectFuncGetAllSubjectsInfo   func()
	afterGetAllSubjectsInfoCounter  uint64
	beforeGetAllSubjectsInfoCounter uint64
	GetAllSubjectsInfoMock          mRepositoryMockGetAllSubjectsInfo

	funcGetStudentInfo          func(id int64) (sp1 *studentInfo, b1 bool)
	inspectFuncGetStudentInfo   func(id int64)
	afterGetStudentInfoCounter  uint64
	beforeGetStudentInfoCounter uint64
	GetStudentInfoMock          mRepositoryMockGetStudentInfo
}

// NewRepositoryMock returns a mock for Repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetAllSubjectsMock = mRepositoryMockGetAllSubjects{mock: m}

	m.GetAllSubjectsInfoMock = mRepositoryMockGetAllSubjectsInfo{mock: m}

	m.GetStudentInfoMock = mRepositoryMockGetStudentInfo{mock: m}
	m.GetStudentInfoMock.callArgs = []*RepositoryMockGetStudentInfoParams{}

	return m
}

type mRepositoryMockGetAllSubjects struct {
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockGetAllSubjectsExpectation
	expectations       []*RepositoryMockGetAllSubjectsExpectation
}

// RepositoryMockGetAllSubjectsExpectation specifies expectation struct of the Repository.GetAllSubjects
type RepositoryMockGetAllSubjectsExpectation struct {
	mock *RepositoryMock

	results *RepositoryMockGetAllSubjectsResults
	Counter uint64
}

// RepositoryMockGetAllSubjectsResults contains results of the Repository.GetAllSubjects
type RepositoryMockGetAllSubjectsResults struct {
	sa1 []string
	b1  bool
}

// Expect sets up expected params for Repository.GetAllSubjects
func (mmGetAllSubjects *mRepositoryMockGetAllSubjects) Expect() *mRepositoryMockGetAllSubjects {
	if mmGetAllSubjects.mock.funcGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("RepositoryMock.GetAllSubjects mock is already set by Set")
	}

	if mmGetAllSubjects.defaultExpectation == nil {
		mmGetAllSubjects.defaultExpectation = &RepositoryMockGetAllSubjectsExpectation{}
	}

	return mmGetAllSubjects
}

// Inspect accepts an inspector function that has same arguments as the Repository.GetAllSubjects
func (mmGetAllSubjects *mRepositoryMockGetAllSubjects) Inspect(f func()) *mRepositoryMockGetAllSubjects {
	if mmGetAllSubjects.mock.inspectFuncGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("Inspect function is already set for RepositoryMock.GetAllSubjects")
	}

	mmGetAllSubjects.mock.inspectFuncGetAllSubjects = f

	return mmGetAllSubjects
}

// Return sets up results that will be returned by Repository.GetAllSubjects
func (mmGetAllSubjects *mRepositoryMockGetAllSubjects) Return(sa1 []string, b1 bool) *RepositoryMock {
	if mmGetAllSubjects.mock.funcGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("RepositoryMock.GetAllSubjects mock is already set by Set")
	}

	if mmGetAllSubjects.defaultExpectation == nil {
		mmGetAllSubjects.defaultExpectation = &RepositoryMockGetAllSubjectsExpectation{mock: mmGetAllSubjects.mock}
	}
	mmGetAllSubjects.defaultExpectation.results = &RepositoryMockGetAllSubjectsResults{sa1, b1}
	return mmGetAllSubjects.mock
}

// Set uses given function f to mock the Repository.GetAllSubjects method
func (mmGetAllSubjects *mRepositoryMockGetAllSubjects) Set(f func() (sa1 []string, b1 bool)) *RepositoryMock {
	if mmGetAllSubjects.defaultExpectation != nil {
		mmGetAllSubjects.mock.t.Fatalf("Default expectation is already set for the Repository.GetAllSubjects method")
	}

	if len(mmGetAllSubjects.expectations) > 0 {
		mmGetAllSubjects.mock.t.Fatalf("Some expectations are already set for the Repository.GetAllSubjects method")
	}

	mmGetAllSubjects.mock.funcGetAllSubjects = f
	return mmGetAllSubjects.mock
}

// GetAllSubjects implements Repository
func (mmGetAllSubjects *RepositoryMock) GetAllSubjects() (sa1 []string, b1 bool) {
	mm_atomic.AddUint64(&mmGetAllSubjects.beforeGetAllSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllSubjects.afterGetAllSubjectsCounter, 1)

	if mmGetAllSubjects.inspectFuncGetAllSubjects != nil {
		mmGetAllSubjects.inspectFuncGetAllSubjects()
	}

	if mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllSubjects.t.Fatal("No results are set for the RepositoryMock.GetAllSubjects")
		}
		return (*mm_results).sa1, (*mm_results).b1
	}
	if mmGetAllSubjects.funcGetAllSubjects != nil {
		return mmGetAllSubjects.funcGetAllSubjects()
	}
	mmGetAllSubjects.t.Fatalf("Unexpected call to RepositoryMock.GetAllSubjects.")
	return
}

// GetAllSubjectsAfterCounter returns a count of finished RepositoryMock.GetAllSubjects invocations
func (mmGetAllSubjects *RepositoryMock) GetAllSubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjects.afterGetAllSubjectsCounter)
}

// GetAllSubjectsBeforeCounter returns a count of RepositoryMock.GetAllSubjects invocations
func (mmGetAllSubjects *RepositoryMock) GetAllSubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjects.beforeGetAllSubjectsCounter)
}

// MinimockGetAllSubjectsDone returns true if the count of the GetAllSubjects invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockGetAllSubjectsDone() bool {
	for _, e := range m.GetAllSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjects != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetAllSubjectsInspect logs each unmet expectation
func (m *RepositoryMock) MinimockGetAllSubjectsInspect() {
	for _, e := range m.GetAllSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepositoryMock.GetAllSubjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetAllSubjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjects != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetAllSubjects")
	}
}

type mRepositoryMockGetAllSubjectsInfo struct {
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockGetAllSubjectsInfoExpectation
	expectations       []*RepositoryMockGetAllSubjectsInfoExpectation
}

// RepositoryMockGetAllSubjectsInfoExpectation specifies expectation struct of the Repository.GetAllSubjectsInfo
type RepositoryMockGetAllSubjectsInfoExpectation struct {
	mock *RepositoryMock

	results *RepositoryMockGetAllSubjectsInfoResults
	Counter uint64
}

// RepositoryMockGetAllSubjectsInfoResults contains results of the Repository.GetAllSubjectsInfo
type RepositoryMockGetAllSubjectsInfoResults struct {
	sa1 []subjectInfo
	b1  bool
}

// Expect sets up expected params for Repository.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepositoryMockGetAllSubjectsInfo) Expect() *mRepositoryMockGetAllSubjectsInfo {
	if mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("RepositoryMock.GetAllSubjectsInfo mock is already set by Set")
	}

	if mmGetAllSubjectsInfo.defaultExpectation == nil {
		mmGetAllSubjectsInfo.defaultExpectation = &RepositoryMockGetAllSubjectsInfoExpectation{}
	}

	return mmGetAllSubjectsInfo
}

// Inspect accepts an inspector function that has same arguments as the Repository.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepositoryMockGetAllSubjectsInfo) Inspect(f func()) *mRepositoryMockGetAllSubjectsInfo {
	if mmGetAllSubjectsInfo.mock.inspectFuncGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Inspect function is already set for RepositoryMock.GetAllSubjectsInfo")
	}

	mmGetAllSubjectsInfo.mock.inspectFuncGetAllSubjectsInfo = f

	return mmGetAllSubjectsInfo
}

// Return sets up results that will be returned by Repository.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepositoryMockGetAllSubjectsInfo) Return(sa1 []subjectInfo, b1 bool) *RepositoryMock {
	if mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("RepositoryMock.GetAllSubjectsInfo mock is already set by Set")
	}

	if mmGetAllSubjectsInfo.defaultExpectation == nil {
		mmGetAllSubjectsInfo.defaultExpectation = &RepositoryMockGetAllSubjectsInfoExpectation{mock: mmGetAllSubjectsInfo.mock}
	}
	mmGetAllSubjectsInfo.defaultExpectation.results = &RepositoryMockGetAllSubjectsInfoResults{sa1, b1}
	return mmGetAllSubjectsInfo.mock
}

// Set uses given function f to mock the Repository.GetAllSubjectsInfo method
func (mmGetAllSubjectsInfo *mRepositoryMockGetAllSubjectsInfo) Set(f func() (sa1 []subjectInfo, b1 bool)) *RepositoryMock {
	if mmGetAllSubjectsInfo.defaultExpectation != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Default expectation is already set for the Repository.GetAllSubjectsInfo method")
	}

	if len(mmGetAllSubjectsInfo.expectations) > 0 {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Some expectations are already set for the Repository.GetAllSubjectsInfo method")
	}

	mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo = f
	return mmGetAllSubjectsInfo.mock
}

// GetAllSubjectsInfo implements Repository
func (mmGetAllSubjectsInfo *RepositoryMock) GetAllSubjectsInfo() (sa1 []subjectInfo, b1 bool) {
	mm_atomic.AddUint64(&mmGetAllSubjectsInfo.beforeGetAllSubjectsInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllSubjectsInfo.afterGetAllSubjectsInfoCounter, 1)

	if mmGetAllSubjectsInfo.inspectFuncGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.inspectFuncGetAllSubjectsInfo()
	}

	if mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation.Counter, 1)

		mm_results := mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllSubjectsInfo.t.Fatal("No results are set for the RepositoryMock.GetAllSubjectsInfo")
		}
		return (*mm_results).sa1, (*mm_results).b1
	}
	if mmGetAllSubjectsInfo.funcGetAllSubjectsInfo != nil {
		return mmGetAllSubjectsInfo.funcGetAllSubjectsInfo()
	}
	mmGetAllSubjectsInfo.t.Fatalf("Unexpected call to RepositoryMock.GetAllSubjectsInfo.")
	return
}

// GetAllSubjectsInfoAfterCounter returns a count of finished RepositoryMock.GetAllSubjectsInfo invocations
func (mmGetAllSubjectsInfo *RepositoryMock) GetAllSubjectsInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjectsInfo.afterGetAllSubjectsInfoCounter)
}

// GetAllSubjectsInfoBeforeCounter returns a count of RepositoryMock.GetAllSubjectsInfo invocations
func (mmGetAllSubjectsInfo *RepositoryMock) GetAllSubjectsInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjectsInfo.beforeGetAllSubjectsInfoCounter)
}

// MinimockGetAllSubjectsInfoDone returns true if the count of the GetAllSubjectsInfo invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockGetAllSubjectsInfoDone() bool {
	for _, e := range m.GetAllSubjectsInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjectsInfo != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetAllSubjectsInfoInspect logs each unmet expectation
func (m *RepositoryMock) MinimockGetAllSubjectsInfoInspect() {
	for _, e := range m.GetAllSubjectsInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepositoryMock.GetAllSubjectsInfo")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetAllSubjectsInfo")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjectsInfo != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetAllSubjectsInfo")
	}
}

type mRepositoryMockGetStudentInfo struct {
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockGetStudentInfoExpectation
	expectations       []*RepositoryMockGetStudentInfoExpectation

	callArgs []*RepositoryMockGetStudentInfoParams
	mutex    sync.RWMutex
}

// RepositoryMockGetStudentInfoExpectation specifies expectation struct of the Repository.GetStudentInfo
type RepositoryMockGetStudentInfoExpectation struct {
	mock    *RepositoryMock
	params  *RepositoryMockGetStudentInfoParams
	results *RepositoryMockGetStudentInfoResults
	Counter uint64
}

// RepositoryMockGetStudentInfoParams contains parameters of the Repository.GetStudentInfo
type RepositoryMockGetStudentInfoParams struct {
	id int64
}

// RepositoryMockGetStudentInfoResults contains results of the Repository.GetStudentInfo
type RepositoryMockGetStudentInfoResults struct {
	sp1 *studentInfo
	b1  bool
}

// Expect sets up expected params for Repository.GetStudentInfo
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) Expect(id int64) *mRepositoryMockGetStudentInfo {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepositoryMock.GetStudentInfo mock is already set by Set")
	}

	if mmGetStudentInfo.defaultExpectation == nil {
		mmGetStudentInfo.defaultExpectation = &RepositoryMockGetStudentInfoExpectation{}
	}

	mmGetStudentInfo.defaultExpectation.params = &RepositoryMockGetStudentInfoParams{id}
	for _, e := range mmGetStudentInfo.expectations {
		if minimock.Equal(e.params, mmGetStudentInfo.defaultExpectation.params) {
			mmGetStudentInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStudentInfo.defaultExpectation.params)
		}
	}

	return mmGetStudentInfo
}

// Inspect accepts an inspector function that has same arguments as the Repository.GetStudentInfo
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) Inspect(f func(id int64)) *mRepositoryMockGetStudentInfo {
	if mmGetStudentInfo.mock.inspectFuncGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("Inspect function is already set for RepositoryMock.GetStudentInfo")
	}

	mmGetStudentInfo.mock.inspectFuncGetStudentInfo = f

	return mmGetStudentInfo
}

// Return sets up results that will be returned by Repository.GetStudentInfo
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) Return(sp1 *studentInfo, b1 bool) *RepositoryMock {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepositoryMock.GetStudentInfo mock is already set by Set")
	}

	if mmGetStudentInfo.defaultExpectation == nil {
		mmGetStudentInfo.defaultExpectation = &RepositoryMockGetStudentInfoExpectation{mock: mmGetStudentInfo.mock}
	}
	mmGetStudentInfo.defaultExpectation.results = &RepositoryMockGetStudentInfoResults{sp1, b1}
	return mmGetStudentInfo.mock
}

// Set uses given function f to mock the Repository.GetStudentInfo method
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) Set(f func(id int64) (sp1 *studentInfo, b1 bool)) *RepositoryMock {
	if mmGetStudentInfo.defaultExpectation != nil {
		mmGetStudentInfo.mock.t.Fatalf("Default expectation is already set for the Repository.GetStudentInfo method")
	}

	if len(mmGetStudentInfo.expectations) > 0 {
		mmGetStudentInfo.mock.t.Fatalf("Some expectations are already set for the Repository.GetStudentInfo method")
	}

	mmGetStudentInfo.mock.funcGetStudentInfo = f
	return mmGetStudentInfo.mock
}

// When sets expectation for the Repository.GetStudentInfo which will trigger the result defined by the following
// Then helper
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) When(id int64) *RepositoryMockGetStudentInfoExpectation {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepositoryMock.GetStudentInfo mock is already set by Set")
	}

	expectation := &RepositoryMockGetStudentInfoExpectation{
		mock:   mmGetStudentInfo.mock,
		params: &RepositoryMockGetStudentInfoParams{id},
	}
	mmGetStudentInfo.expectations = append(mmGetStudentInfo.expectations, expectation)
	return expectation
}

// Then sets up Repository.GetStudentInfo return parameters for the expectation previously defined by the When method
func (e *RepositoryMockGetStudentInfoExpectation) Then(sp1 *studentInfo, b1 bool) *RepositoryMock {
	e.results = &RepositoryMockGetStudentInfoResults{sp1, b1}
	return e.mock
}

// GetStudentInfo implements Repository
func (mmGetStudentInfo *RepositoryMock) GetStudentInfo(id int64) (sp1 *studentInfo, b1 bool) {
	mm_atomic.AddUint64(&mmGetStudentInfo.beforeGetStudentInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStudentInfo.afterGetStudentInfoCounter, 1)

	if mmGetStudentInfo.inspectFuncGetStudentInfo != nil {
		mmGetStudentInfo.inspectFuncGetStudentInfo(id)
	}

	mm_params := &RepositoryMockGetStudentInfoParams{id}

	// Record call args
	mmGetStudentInfo.GetStudentInfoMock.mutex.Lock()
	mmGetStudentInfo.GetStudentInfoMock.callArgs = append(mmGetStudentInfo.GetStudentInfoMock.callArgs, mm_params)
	mmGetStudentInfo.GetStudentInfoMock.mutex.Unlock()

	for _, e := range mmGetStudentInfo.GetStudentInfoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.b1
		}
	}

	if mmGetStudentInfo.GetStudentInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.params
		mm_got := RepositoryMockGetStudentInfoParams{id}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStudentInfo.t.Errorf("RepositoryMock.GetStudentInfo got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStudentInfo.t.Fatal("No results are set for the RepositoryMock.GetStudentInfo")
		}
		return (*mm_results).sp1, (*mm_results).b1
	}
	if mmGetStudentInfo.funcGetStudentInfo != nil {
		return mmGetStudentInfo.funcGetStudentInfo(id)
	}
	mmGetStudentInfo.t.Fatalf("Unexpected call to RepositoryMock.GetStudentInfo. %v", id)
	return
}

// GetStudentInfoAfterCounter returns a count of finished RepositoryMock.GetStudentInfo invocations
func (mmGetStudentInfo *RepositoryMock) GetStudentInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStudentInfo.afterGetStudentInfoCounter)
}

// GetStudentInfoBeforeCounter returns a count of RepositoryMock.GetStudentInfo invocations
func (mmGetStudentInfo *RepositoryMock) GetStudentInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStudentInfo.beforeGetStudentInfoCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.GetStudentInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStudentInfo *mRepositoryMockGetStudentInfo) Calls() []*RepositoryMockGetStudentInfoParams {
	mmGetStudentInfo.mutex.RLock()

	argCopy := make([]*RepositoryMockGetStudentInfoParams, len(mmGetStudentInfo.callArgs))
	copy(argCopy, mmGetStudentInfo.callArgs)

	mmGetStudentInfo.mutex.RUnlock()

	return argCopy
}

// MinimockGetStudentInfoDone returns true if the count of the GetStudentInfo invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockGetStudentInfoDone() bool {
	for _, e := range m.GetStudentInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetStudentInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStudentInfo != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetStudentInfoInspect logs each unmet expectation
func (m *RepositoryMock) MinimockGetStudentInfoInspect() {
	for _, e := range m.GetStudentInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.GetStudentInfo with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetStudentInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		if m.GetStudentInfoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepositoryMock.GetStudentInfo")
		} else {
			m.t.Errorf("Expected call to RepositoryMock.GetStudentInfo with params: %#v", *m.GetStudentInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStudentInfo != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetStudentInfo")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetAllSubjectsInspect()

		m.MinimockGetAllSubjectsInfoInspect()

		m.MinimockGetStudentInfoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetAllSubjectsDone() &&
		m.MinimockGetAllSubjectsInfoDone() &&
		m.MinimockGetStudentInfoDone()
}
