package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.TutorService -o ./tutor_service_mock.go -n TutorServiceMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TutorServiceMock implements TutorService
type TutorServiceMock struct {
	t minimock.Tester

	funcSubjects          func() (sa1 []string)
	inspectFuncSubjects   func()
	afterSubjectsCounter  uint64
	beforeSubjectsCounter uint64
	SubjectsMock          mTutorServiceMockSubjects

	funcTutorsID          func(subject string) (ia1 []int64)
	inspectFuncTutorsID   func(subject string)
	afterTutorsIDCounter  uint64
	beforeTutorsIDCounter uint64
	TutorsIDMock          mTutorServiceMockTutorsID
}

// NewTutorServiceMock returns a mock for TutorService
func NewTutorServiceMock(t minimock.Tester) *TutorServiceMock {
	m := &TutorServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SubjectsMock = mTutorServiceMockSubjects{mock: m}

	m.TutorsIDMock = mTutorServiceMockTutorsID{mock: m}
	m.TutorsIDMock.callArgs = []*TutorServiceMockTutorsIDParams{}

	return m
}

type mTutorServiceMockSubjects struct {
	mock               *TutorServiceMock
	defaultExpectation *TutorServiceMockSubjectsExpectation
	expectations       []*TutorServiceMockSubjectsExpectation
}

// TutorServiceMockSubjectsExpectation specifies expectation struct of the TutorService.Subjects
type TutorServiceMockSubjectsExpectation struct {
	mock *TutorServiceMock

	results *TutorServiceMockSubjectsResults
	Counter uint64
}

// TutorServiceMockSubjectsResults contains results of the TutorService.Subjects
type TutorServiceMockSubjectsResults struct {
	sa1 []string
}

// Expect sets up expected params for TutorService.Subjects
func (mmSubjects *mTutorServiceMockSubjects) Expect() *mTutorServiceMockSubjects {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("TutorServiceMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &TutorServiceMockSubjectsExpectation{}
	}

	return mmSubjects
}

// Inspect accepts an inspector function that has same arguments as the TutorService.Subjects
func (mmSubjects *mTutorServiceMockSubjects) Inspect(f func()) *mTutorServiceMockSubjects {
	if mmSubjects.mock.inspectFuncSubjects != nil {
		mmSubjects.mock.t.Fatalf("Inspect function is already set for TutorServiceMock.Subjects")
	}

	mmSubjects.mock.inspectFuncSubjects = f

	return mmSubjects
}

// Return sets up results that will be returned by TutorService.Subjects
func (mmSubjects *mTutorServiceMockSubjects) Return(sa1 []string) *TutorServiceMock {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("TutorServiceMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &TutorServiceMockSubjectsExpectation{mock: mmSubjects.mock}
	}
	mmSubjects.defaultExpectation.results = &TutorServiceMockSubjectsResults{sa1}
	return mmSubjects.mock
}

// Set uses given function f to mock the TutorService.Subjects method
func (mmSubjects *mTutorServiceMockSubjects) Set(f func() (sa1 []string)) *TutorServiceMock {
	if mmSubjects.defaultExpectation != nil {
		mmSubjects.mock.t.Fatalf("Default expectation is already set for the TutorService.Subjects method")
	}

	if len(mmSubjects.expectations) > 0 {
		mmSubjects.mock.t.Fatalf("Some expectations are already set for the TutorService.Subjects method")
	}

	mmSubjects.mock.funcSubjects = f
	return mmSubjects.mock
}

// Subjects implements TutorService
func (mmSubjects *TutorServiceMock) Subjects() (sa1 []string) {
	mm_atomic.AddUint64(&mmSubjects.beforeSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmSubjects.afterSubjectsCounter, 1)

	if mmSubjects.inspectFuncSubjects != nil {
		mmSubjects.inspectFuncSubjects()
	}

	if mmSubjects.SubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSubjects.SubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmSubjects.SubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmSubjects.t.Fatal("No results are set for the TutorServiceMock.Subjects")
		}
		return (*mm_results).sa1
	}
	if mmSubjects.funcSubjects != nil {
		return mmSubjects.funcSubjects()
	}
	mmSubjects.t.Fatalf("Unexpected call to TutorServiceMock.Subjects.")
	return
}

// SubjectsAfterCounter returns a count of finished TutorServiceMock.Subjects invocations
func (mmSubjects *TutorServiceMock) SubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.afterSubjectsCounter)
}

// SubjectsBeforeCounter returns a count of TutorServiceMock.Subjects invocations
func (mmSubjects *TutorServiceMock) SubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.beforeSubjectsCounter)
}

// MinimockSubjectsDone returns true if the count of the Subjects invocations corresponds
// the number of defined expectations
func (m *TutorServiceMock) MinimockSubjectsDone() bool {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockSubjectsInspect logs each unmet expectation
func (m *TutorServiceMock) MinimockSubjectsInspect() {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to TutorServiceMock.Subjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to TutorServiceMock.Subjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to TutorServiceMock.Subjects")
	}
}

type mTutorServiceMockTutorsID struct {
	mock               *TutorServiceMock
	defaultExpectation *TutorServiceMockTutorsIDExpectation
	expectations       []*TutorServiceMockTutorsIDExpectation

	callArgs []*TutorServiceMockTutorsIDParams
	mutex    sync.RWMutex
}

// TutorServiceMockTutorsIDExpectation specifies expectation struct of the TutorService.TutorsID
type TutorServiceMockTutorsIDExpectation struct {
	mock    *TutorServiceMock
	params  *TutorServiceMockTutorsIDParams
	results *TutorServiceMockTutorsIDResults
	Counter uint64
}

// TutorServiceMockTutorsIDParams contains parameters of the TutorService.TutorsID
type TutorServiceMockTutorsIDParams struct {
	subject string
}

// TutorServiceMockTutorsIDResults contains results of the TutorService.TutorsID
type TutorServiceMockTutorsIDResults struct {
	ia1 []int64
}

// Expect sets up expected params for TutorService.TutorsID
func (mmTutorsID *mTutorServiceMockTutorsID) Expect(subject string) *mTutorServiceMockTutorsID {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &TutorServiceMockTutorsIDExpectation{}
	}

	mmTutorsID.defaultExpectation.params = &TutorServiceMockTutorsIDParams{subject}
	for _, e := range mmTutorsID.expectations {
		if minimock.Equal(e.params, mmTutorsID.defaultExpectation.params) {
			mmTutorsID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTutorsID.defaultExpectation.params)
		}
	}

	return mmTutorsID
}

// Inspect accepts an inspector function that has same arguments as the TutorService.TutorsID
func (mmTutorsID *mTutorServiceMockTutorsID) Inspect(f func(subject string)) *mTutorServiceMockTutorsID {
	if mmTutorsID.mock.inspectFuncTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("Inspect function is already set for TutorServiceMock.TutorsID")
	}

	mmTutorsID.mock.inspectFuncTutorsID = f

	return mmTutorsID
}

// Return sets up results that will be returned by TutorService.TutorsID
func (mmTutorsID *mTutorServiceMockTutorsID) Return(ia1 []int64) *TutorServiceMock {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &TutorServiceMockTutorsIDExpectation{mock: mmTutorsID.mock}
	}
	mmTutorsID.defaultExpectation.results = &TutorServiceMockTutorsIDResults{ia1}
	return mmTutorsID.mock
}

// Set uses given function f to mock the TutorService.TutorsID method
func (mmTutorsID *mTutorServiceMockTutorsID) Set(f func(subject string) (ia1 []int64)) *TutorServiceMock {
	if mmTutorsID.defaultExpectation != nil {
		mmTutorsID.mock.t.Fatalf("Default expectation is already set for the TutorService.TutorsID method")
	}

	if len(mmTutorsID.expectations) > 0 {
		mmTutorsID.mock.t.Fatalf("Some expectations are already set for the TutorService.TutorsID method")
	}

	mmTutorsID.mock.funcTutorsID = f
	return mmTutorsID.mock
}

// When sets expectation for the TutorService.TutorsID which will trigger the result defined by the following
// Then helper
func (mmTutorsID *mTutorServiceMockTutorsID) When(subject string) *TutorServiceMockTutorsIDExpectation {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceMock.TutorsID mock is already set by Set")
	}

	expectation := &TutorServiceMockTutorsIDExpectation{
		mock:   mmTutorsID.mock,
		params: &TutorServiceMockTutorsIDParams{subject},
	}
	mmTutorsID.expectations = append(mmTutorsID.expectations, expectation)
	return expectation
}

// Then sets up TutorService.TutorsID return parameters for the expectation previously defined by the When method
func (e *TutorServiceMockTutorsIDExpectation) Then(ia1 []int64) *TutorServiceMock {
	e.results = &TutorServiceMockTutorsIDResults{ia1}
	return e.mock
}

// TutorsID implements TutorService
func (mmTutorsID *TutorServiceMock) TutorsID(subject string) (ia1 []int64) {
	mm_atomic.AddUint64(&mmTutorsID.beforeTutorsIDCounter, 1)
	defer mm_atomic.AddUint64(&mmTutorsID.afterTutorsIDCounter, 1)

	if mmTutorsID.inspectFuncTutorsID != nil {
		mmTutorsID.inspectFuncTutorsID(subject)
	}

	mm_params := &TutorServiceMockTutorsIDParams{subject}

	// Record call args
	mmTutorsID.TutorsIDMock.mutex.Lock()
	mmTutorsID.TutorsIDMock.callArgs = append(mmTutorsID.TutorsIDMock.callArgs, mm_params)
	mmTutorsID.TutorsIDMock.mutex.Unlock()

	for _, e := range mmTutorsID.TutorsIDMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ia1
		}
	}

	if mmTutorsID.TutorsIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTutorsID.TutorsIDMock.defaultExpectation.Counter, 1)
		mm_want := mmTutorsID.TutorsIDMock.defaultExpectation.params
		mm_got := TutorServiceMockTutorsIDParams{subject}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTutorsID.t.Errorf("TutorServiceMock.TutorsID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTutorsID.TutorsIDMock.defaultExpectation.results
		if mm_results == nil {
			mmTutorsID.t.Fatal("No results are set for the TutorServiceMock.TutorsID")
		}
		return (*mm_results).ia1
	}
	if mmTutorsID.funcTutorsID != nil {
		return mmTutorsID.funcTutorsID(subject)
	}
	mmTutorsID.t.Fatalf("Unexpected call to TutorServiceMock.TutorsID. %v", subject)
	return
}

// TutorsIDAfterCounter returns a count of finished TutorServiceMock.TutorsID invocations
func (mmTutorsID *TutorServiceMock) TutorsIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.afterTutorsIDCounter)
}

// TutorsIDBeforeCounter returns a count of TutorServiceMock.TutorsID invocations
func (mmTutorsID *TutorServiceMock) TutorsIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.beforeTutorsIDCounter)
}

// Calls returns a list of arguments used in each call to TutorServiceMock.TutorsID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTutorsID *mTutorServiceMockTutorsID) Calls() []*TutorServiceMockTutorsIDParams {
	mmTutorsID.mutex.RLock()

	argCopy := make([]*TutorServiceMockTutorsIDParams, len(mmTutorsID.callArgs))
	copy(argCopy, mmTutorsID.callArgs)

	mmTutorsID.mutex.RUnlock()

	return argCopy
}

// MinimockTutorsIDDone returns true if the count of the TutorsID invocations corresponds
// the number of defined expectations
func (m *TutorServiceMock) MinimockTutorsIDDone() bool {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	return true
}

// MinimockTutorsIDInspect logs each unmet expectation
func (m *TutorServiceMock) MinimockTutorsIDInspect() {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TutorServiceMock.TutorsID with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		if m.TutorsIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TutorServiceMock.TutorsID")
		} else {
			m.t.Errorf("Expected call to TutorServiceMock.TutorsID with params: %#v", *m.TutorsIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		m.t.Error("Expected call to TutorServiceMock.TutorsID")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TutorServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSubjectsInspect()

		m.MinimockTutorsIDInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TutorServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TutorServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSubjectsDone() &&
		m.MinimockTutorsIDDone()
}
