name: Kotlin hw 6 check

on:
    pull_request:
        types:
        - opened
        - synchronize

jobs:
    build:
        runs-on: [self-hosted, kotlin]
        timeout-minutes: 5
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: 17
              distribution: adopt
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 8.2
            generate-job-summary: false
        - name: Build with Gradle
          run: ./gradlew build
        - name: Upload ktlint check report
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: ktlint check report
            path: build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
            retention-days: 1
