workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test

lint-job:
  when: always
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run

test-job:
  when: always
  stage: test
  image: golang:latest
  script:
    - go test ./...
